development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: mercury_demo_developement
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: mercury_demo_developement
  username: root
  password:
